export enum ProjectType {
  INTERVIEW = "INTERVIEW",
  PROTOTYPE_TESTING = "PROTOTYPE_TESTING",
}

export enum ProjectCreationStepEnum {
  DRIVING_NEED = "DRIVING_NEED",
  RESEARCH_QUESTIONS = "RESEARCH_QUESTIONS",
  SUCCESS_CRITERIA = "SUCCESS_CRITERIA",
  RECRUITING_CRITERIA = "RECRUITING_CRITERIA",
  SPECIFIC_GUIDELINES = "SPECIFIC_GUIDELINES",
}

export enum PrototypeCreationStepEnum {
  TASK_DEFINITION = "TASK_DEFINITION",
  PROTOTYPE_LINK_IMPORT = "PROTOTYPE_LINK_IMPORT",
  SPECIFIC_GUIDELINES = "SPECIFIC_GUIDELINES",
}

export enum StepStatus {
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  NOT_STARTED = "NOT_STARTED",
  FAILED = "FAILED",
}
